### ISSUE TITLE
database

### ISSUE THREAD

**Issue by phu1110** [Yersin-K18/BookStore#4]

**Comment by hoang3402** [comment]
@phu1110 up vào đây đi

**Comment by phu1110** [comment]
[script.zip](https://github.com/Yersin-K18/BookStore/files/11741929/script.zip)
để thẳng sql ko đc nên t nén zip nha

**Comment by hoang3402** [comment]
![image](https://github.com/Yersin-K18/BookStore/assets/54090585/8f0ac1d2-1d32-4bd1-89f7-aaa828c097a1)

**Comment by hoang3402** [comment]
Info database: 
name: yersin_db
host: sql.bsite.net\MSSQL2016
username: yersin_db
pass: k8eHarwdXQH.AJg

**Comment by hoang3402** [comment]
@vule2303
